Update jitpack.yml: use short commit hash ${GITHUB_SHA:0:7} and show log

diff --git a/.github/workflows/jitpack.yml b/.github/workflows/jitpack.yml
--- a/.github/workflows/jitpack.yml
+++ b/.github/workflows/jitpack.yml
@@ -9,11 +9,34 @@ jobs:
   check-artifact:
     runs-on: ubuntu-latest
     steps:
-      - name: Download Jitpack Artifact
+      - name: Download and show log by commit hash
+        run: |
+          URL="https://jitpack.io/com/github/nbauma109/jd-gui-duo/${GITHUB_SHA:0:7}/build.log"
+          echo "Downloading URL $URL"
+          curl --location --fail --connect-timeout 3000 --max-time 6000 "$URL"
+      - name: Download Jitpack Artifact by commit hash
+        run: |
+          URL="https://jitpack.io/com/github/nbauma109/jd-gui-duo/jd-gui-duo/${GITHUB_SHA:0:7}/jd-gui-duo-${GITHUB_SHA:0:7}.zip"
+          echo "Downloading URL $URL"
+          curl --location --fail --connect-timeout 3000 --max-time 6000 "$URL" --output "jd-gui-duo-${GITHUB_SHA:0:7}.zip"
+      - name: Check if the ZIP file is valid
+        run: |
+          if unzip -tq "jd-gui-duo-${GITHUB_SHA:0:7}.zip"; then
+            echo "The ZIP file is valid."
+          else
+            echo "The ZIP file is invalid."
+            exit 1
+          fi
+      - name: Download and show log by branch SNAPSHOT
+        run: |
+          URL="https://jitpack.io/com/github/nbauma109/jd-gui-duo/${GITHUB_REF##*/}-SNAPSHOT/build.log"
+          echo "Downloading URL $URL"
+          curl --location --fail --connect-timeout 3000 --max-time 6000 "$URL"
+      - name: Download Jitpack Artifact by branch SNAPSHOT
         run: |
           URL="https://jitpack.io/com/github/nbauma109/jd-gui-duo/jd-gui-duo/${GITHUB_REF##*/}-SNAPSHOT/jd-gui-duo-${GITHUB_REF##*/}-SNAPSHOT.zip"
           echo "Downloading URL $URL"
-          curl --location --fail --connect-timeout 300 --max-time 600 "$URL" --output "jd-gui-duo-${GITHUB_REF##*/}-SNAPSHOT.zip"
+          curl --location --fail --connect-timeout 3000 --max-time 6000 "$URL" --output "jd-gui-duo-${GITHUB_REF##*/}-SNAPSHOT.zip"
       - name: Check if the ZIP file is valid
         run: |
           if unzip -tq "jd-gui-duo-${GITHUB_REF##*/}-SNAPSHOT.zip"; then
